green_valley/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('products.urls')),

    path('accounts/', include('allauth.urls')),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

greenvalley/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('products.urls')),

    path('accounts/', include('allauth.urls')),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),
    path('select-group/', views.selectGroup, name='select-group'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.editProfile, name='edit-profile'),
    path('edit-farm/', views.editFarm, name='edit-farm'),

    path('farms/', views.farms, name='farms'),
    path('farm/<str:pk>/', views.farm, name='farm'),



    path('', views.frontpage, name='frontpage'),
    path('home/', views.home, name='home'),


]

products/models.py
from django.db import models
from users.models import Profile, Farm
from django.utils import timezone
from django.core.validators import MinValueValidator
from django.db.models import Avg
import uuid

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(max_length=200, unique=True)
    category_id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name


UNIT_CHOICES = (
        ('kg', 'kilogrami'),
        ('g', 'grami'),
        ('l', 'litri'),
        ('ml', 'mililitri'),
        ('gab', 'gabalā'),
    )

class Product(models.Model):
    product_id = models.UUIDField(default=uuid.uuid4, unique=True,
                                  primary_key=True, editable=False)
    farm = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    category = models.ForeignKey(
        ProductCategory, on_delete=models.CASCADE, )
    description = models.TextField()
    foto = models.ImageField(upload_to='product_images/')

    price = models.DecimalField(
        max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])

    unit = models.CharField(max_length=20, choices=UNIT_CHOICES, default='gab')
    date = models.DateTimeField(default=timezone.now)

    def average_rating(self) -> float:
        return Rating.objects.filter(product=self).aggregate(Avg("rating"))["rating__avg"] or 0


    def __str__(self):
        return self.name

class Rating(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)
    def __str__(self):
        return str(self.user.username)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import uuid
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut
from django.core.validators import RegexValidator


class Profile(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    username = models.CharField(max_length=200, )
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=500, )
    foto = models.ImageField(upload_to='profile_images/',
                             null=True, blank=False, default='default_profile.jpg',)
    phone_regex = RegexValidator(
        regex=r'^\d{8}$'
    )
    phone = models.CharField(
        max_length=8,
        blank=True,
        null=True,
        validators=[phone_regex]
    )
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        if not self.id:
            if self.user:
                self.first_name = self.user.first_name
                self.last_name = self.user.last_name
        super(Profile, self).save(*args, **kwargs)


class Farm(models.Model):
    owner = models.OneToOneField(
        Profile, on_delete=models.CASCADE, blank=True, null=True
    )
    name = models.CharField(max_length=200)
    description = models.TextField()

    foto = models.ImageField(upload_to='farm_images/', null=True, blank=False,
                             default='default_farm.jpg',)
    phone_regex = RegexValidator(
        regex=r'^\d{8}$'
    )
    phone = models.CharField(
        max_length=8,
        blank=True,
        null=True,
        validators=[phone_regex]
    )
    country = models.CharField(max_length=200, default="Latvija")
    city = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    latitude = models.CharField(max_length=200, blank=True, null=True)
    longitude = models.CharField(max_length=200, blank=True, null=True)
    date = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        if self.country and self.city and self.address:
            address = f"{self.country}, {self.city}, {self.address}"
            latitude, longitude = geocode_address(address)
            if latitude is not None and longitude is not None:
                self.latitude = str(latitude)
                self.longitude = str(longitude)
        super(Farm, self).save(*args, **kwargs)


def geocode_address(address):
    geolocator = Nominatim(user_agent='my_app_name')
    try:
        location = geolocator.geocode(address)
        if location is not None:
            return location.latitude, location.longitude
        return None, None
    except GeocoderTimedOut:
        return geocode_address(address)


class Client (models.Model):
    person = models.OneToOneField(
        Profile, on_delete=models.CASCADE, blank=True, null=True
    )
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    foto = models.ImageField(null=True, blank=False,
                             default='default_profile.jpg',)

users/forms.py
from pyexpat import model
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Farm, Client
from django import forms


class UserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        self.fields['username'].label = 'Lietotājvārds'
        self.fields['email'].label = 'E-pasts'
        self.fields['password1'].label = 'Parole'
        self.fields['password2'].label = 'Parole vēlreiz'

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user', 'date', 'username']

        labels = {
            'first_name': 'Vārds:',
            'last_name': 'Uzvārds:',
            'foto': 'Fotogrāfija:',    
            'email': 'E-pasts:',
            'phone': 'Tālrunis:',
        }


    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

class FarmForm(ModelForm):
    class Meta:
        model = Farm
        fields = '__all__'
        exclude = ['owner', 'date', 'longitude', 'latitude']

        labels = {
            'name': 'Saimniecības nosaukums:',
            'description': 'Apraksts:',
            'foto': 'Fotogrāfija:',
            'phone': 'Tālrunis:',
            'country': 'Valsts:',
            'city': 'Pilsēta:',
            'address': 'Adrese:',
        }


    def __init__(self, *args, **kwargs):
        super(FarmForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

users/views.py
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.models import User, Group
from .forms import UserCreationForm, ProfileForm, FarmForm
from .models import Profile, Farm, Client
from .utils import searchFarms, paginateFarms


from .decorators import unauthenticated_user


@unauthenticated_user
def loginUser(request):
    page = 'login'
    if request.method == 'POST':
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(request.GET['next'] if 'next' in request.GET else 'home')
        else:
            messages.error(request, 'Username or password is incorrect')

    return render(request, 'users/login_register.html')


@unauthenticated_user
def registerUser(request):
    page = 'register'
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data.get('username')

            user.username = user.username.lower()
            user.save()

            return render(request, 'users/select_group.html', {'user_id': user.id})

    context = {'page': page, 'form': form}
    return render(request, 'users/login_register.html', context)


def logoutUser(request):
    logout(request)
    return redirect('login')


def selectGroup(request):
    if request.method == 'POST':
        group_name = request.POST.get('group')
        user_id = request.POST.get('user_id')

        group = Group.objects.get(name=group_name)
        user = User.objects.get(id=user_id)
        user.groups.add(group)
        user.save()

        profile = Profile.objects.get(user=user)
        profile.username = user.username
        profile.email = user.email
        profile.save()

        if group_name == 'farm':
            Farm.objects.create(owner=profile)
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('edit-farm')

        elif group_name == 'client':
            Client.objects.create(person=profile)
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('edit-profile')

    return render(request, 'users/select_group.html')


def frontpage(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        return render(request, 'users/frontpage.html')


@login_required(login_url='login')
def profile(request):

    profile = request.user.profile
    group = request.user.groups.all()[0].name
    page = None
    if group == 'farm':
        page = 'farm'
    elif group == 'client':
        page = 'client'

    context = {'profile': profile, 'page': page}
    return render(request, 'users/profile.html', context)


@login_required(login_url='login')
def editProfile(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()

            return redirect('profile')
    context = {'form': form}
    return render(request, 'users/profile_form.html', context)


@login_required(login_url='login')
def editFarm(request):
    profile = request.user.profile
    farm = profile.farm

    if farm is None:
        farm = Farm(owner=profile)

    form = FarmForm(instance=farm)

    if request.method == 'POST':
        form = FarmForm(request.POST, request.FILES, instance=farm)
        if form.is_valid():
            farm = form.save(commit=False)
            farm.owner = profile
            farm.save()

            return redirect('profile')

    context = {'form': form}
    return render(request, 'users/farm_form.html', context)


@login_required(login_url='login')
def home(request):
    user_profile = request.user.profile
    user_groups = request.user.groups.values_list('name', flat=True)
    if 'client' in user_groups or 'farm' in user_groups:
        return redirect('profile')
    else:
        user = request.user
        return render(request, 'users/select_group.html', {'user_id': user.id})


def farms(request):
    farms, search_query = searchFarms(request)
    farms = farms.order_by('-date')
    custom_range, farms = paginateFarms(request, farms, 6)
    context = {'farms': farms, 'search_query': search_query,
               'custom_range': custom_range}
    return render(request, 'users/farms.html', context)


def farm(request, pk):
    try:
        farm = Farm.objects.get(id=pk)
        latitude = float(farm.latitude) if farm.latitude else None
        longitude = float(farm.longitude) if farm.longitude else None
    except (Farm.DoesNotExist, ValueError):
        farm = None
        latitude = None
        longitude = None

    context = {'farm': farm, 'latitude': latitude, 'longitude': longitude}
    return render(request, 'users/farm.html', context)

users/templates/users/farm.html
{% extends 'main.html' %} {% block content %}
<div class="container" style="margin-top: 3rem">
  <div class="row" id="features">
    <div class="col-sm-7 feature">
      <img
        src="{{ farm.foto.url }}"
        alt="Web Design"
        class="img-circle"
        style="width: 100%"
      />
      {% if farm and latitude and longitude %}
      <div id="map"></div>
      <script>
        var latitude = {{ farm.latitude|floatformat:"-2" }};
        var longitude = {{ farm.longitude|floatformat:"-2" }};
        window.onload = function() {
            initMap(latitude, longitude);
        };
      </script>
      {% endif %}
    </div>
    <!--END feature-->

    <div class="col-sm-5 feature">
      <h1>{{farm.name}}</h1>
      <p>{{farm.description}}</p>
      <p>E-pasts: {{farm.owner.email}}</p>
      <p>Lokācija: {{farm.city}} / {{farm.address}}</p>
    </div>
    <!--END feature-->
  </div>
  <!--end features-->
</div>

<div class="row row-cols-1 row-cols-md-4 g-4" style="margin: 1rem">
  {% for product in farm.owner.product_set.all %}
  <div class="col" style="margin-top: 1rem">
    <div class="card h-100">
      <div>
        <a href="{% url 'product' product.product_id %}" class="card__body">
          <img src="{{ product.foto.url }}" class="card-img-top" alt="image"
        /></a>
      </div>
      <div class="card-body">
        <a href="{% url 'product' product.product_id %}">
          <h5 class="card-title">{{ product.name }}</h5></a
        >

        <p class="card-text">{{ product.price }} € / {{ product.unit}}</p>
        {% comment %}
        <p class="card-text">{{ product.saimnieciba.s_nosaukums}}</p>
        {% endcomment %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}

users/templates/users/farm_form.html
{% extends "main.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="container dform">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form|crispy }}
    <button class="btn btn-secondary type="submit">Saglabāt</button>
  </form>
</div>
{% endblock content %}

users/templates/users/farms.html
{% extends 'main.html' %} {% block content %}

<form
  id="searchForm"
  class="form d-flex justify-content-center mt-4"
  action="{% url 'farms' %}"
  method="get"
>
  <div class="input-group input-group-lg" style="width: 40%">
    <input
      class="form-control"
      id="formInputSearch"
      type="text"
      name="search_query"
      placeholder="Meklēt saimniecību"
      value="{{search_query}}"
    />
    <button class="btn btn-secondary" type="submit">
      <i class="fas fa-search"></i>
    </button>
  </div>
</form>

<div class="row row-cols-1 row-cols-md-3 g-4" style="margin: 1rem">
  {% for farm in farms %}
  <div class="col" style="margin-top: 1rem">
    <div class="card h-100">
      <div>
        <a href="{% url 'farm' farm.id %}" class="card__body">
          <img
            src="{{ farm.foto.url }}"
            class="card-img-top farm"
            alt="image"
          />
        </a>
      </div>
      <div class="card-body">
        <a href="{% url 'farm' farm.id %}">
          <h5 class="card-title">{{ farm.name }}</h5>
        </a>
        <p class="card-text">{{ farm.description|truncatewords_html:30 }}</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">{{farm.city}} / {{farm.address}}</small>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% include 'pagination.html' with queryset=farms custom_range=custom_range %}
<!--  -->
{% endblock content %}

users/templates/users/frontpage.html
{% extends 'main.html' %} {% block content %} {% load static %}
<div class="hero-image">
  <div class="hero-text">
    <h1 class="title">Green Valley</h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="teksts">
        <h2 class="text-center">Green Valley</h2>
        <p class="text-center">
          Vietne vietējo ražotāju produktu vai pakalpojumu reklamēšanai un
          sasaistei ar potenciālo klientu
        </p>
        <h3>Iespējas</h3>
        <ul>
          <li>
            Publicēt piedāvāto produktu vai pakalpojumu vietnē, ko redzēs citi
            tās lietotāji, un ieinteresētās personas spēs ar jums kontaktēties
            vai pat norēķināties
          </li>
          <p></p>
          <li>
            Iepazīties ar vietējajām saimniecībām un to piedāvātajiem labumiem
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      <img src="{% static 'images/frontpage_image.jpg' %}" class="img-fluid" />
    </div>
  </div>
</div>

{% endblock content %}

users/templates/users/login_register.html
{% extends 'main.html' %} {% load socialaccount %} {% providers_media_js %}
<!--  -->
{% block content %} {% if page == 'register' %}
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-4">
      <div class="card shadow">
        <div class="card-body">
          <form action="{% url 'register' %}" method="POST">
            {% csrf_token %} {% for field in form %}
            <div class="mb-3 row">
              <label
                for="{{field.id_for_label}}"
                class="col-sm-4 col-form-label"
                >{{field.label}}</label
              >
              <div class="col-sm-8">
                {{field}} {% for error in field.errors %}
                <p class="text-danger">{{error}}</p>
                {% endfor %}
              </div>
            </div>
            {% endfor %}

            <div class="text-center">
              <button type="submit" class="btn btn-primary">
                Reģistrēties
              </button>
              <button class="btn">
                <a
                  class="btn btn-lg btn-google btn-block"
                  href="{% provider_login_url 'google' %}"
                  ><img
                    src="https://img.icons8.com/color/16/000000/google-logo.png"
                  />
                  Pievienoties ar Google</a
                >
              </button>
            </div>
          </form>
        </div>
        <div class="card-footer text-center">
          <p>Jau esi reģistrējies? <a href="{% url 'login' %}">Ienākt</a></p>
        </div>
      </div>
    </div>
  </div>
</div>

{% else %}
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-4">
      <div class="card shadow">
        <div class="card-body">
          <form method="POST" action="" class="form">
            {% csrf_token %}
            <div class="mb-3">
              <label for="username" class="form-label">Lietotājvārds</label>
              <input
                type="text"
                class="form-control"
                id="username"
                name="username"
                placeholder="Enter your username..."
              />
            </div>
            <div class="mb-3">
              <label for="password" class="form-label">Parole</label>
              <input
                type="password"
                class="form-control"
                id="password"
                name="password"
                placeholder="••••••••"
              />
            </div>
            <div class="text-center">
              <button type="submit" class="btn btn-primary">
                Pievienoties
              </button>

              <button class="btn">
                <a
                  class="btn btn-lg btn-google btn-block"
                  href="{% provider_login_url 'google' %}?next=/home/"
                  ><img
                    src="https://img.icons8.com/color/16/000000/google-logo.png"
                  />
                  Pievienoties ar Google</a
                >
              </button>
            </div>
          </form>
        </div>
        <div class="text-center card-footer mt-0">
          <p>
            Neesi reģistrējies? <a href="{% url 'register' %}">Reģistrēties</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endif %} {% endblock %}

users/templates/users/profile.html
{% extends 'main.html' %} {% block content %} {% if page == 'farm' %}

<div class="container" style="margin-top: 3rem">
  <div class="row" id="features">
    <div class="col-sm-7 feature text-center">
      <img src="{{ profile.farm.foto.url }}" class="prof_pic" />
    </div>
    <div class="col-sm-5 feature">
      <h1>{{profile.farm.name}}</h1>
      <p>{{profile.farm.description}}</p>
      <p>{{profile.address}}</p>
      <div class="container">
        <button type="button" class="btn btn-secondary">
          <a href="{% url 'edit-farm' %}">Rediģēt profilu</a>
        </button>
        <button type="button" class="btn btn-secondary">
          <a href="{% url 'add-product' %}">Pievienot produktu</a>
        </button>
      </div>
    </div>
  </div>
</div>

<div class="row row-cols-1 row-cols-md-4 g-4" style="margin: 1rem">
  {% for product in profile.product_set.all reversed %}
  <div class="col" style="margin-top: 1rem">
    <div class="card h-100">
      <div>
        <a href="{% url 'product' product.product_id %}" class="card__body">
          <img src="{{ product.foto.url }}" class="card-img-top" alt="image"
        /></a>
      </div>
      <div class="card-body">
        <a href="{% url 'product' product.product_id %}"
          ><h5 class="card-title">{{ product.name }}</h5></a
        >
        <p class="card-text">{{ product.price }} € / {{ product.unit}}</p>
        <button type="button" class="btn btn-secondary">
          <a class="edit" href="{% url 'update-product' product.product_id %}"
            >Rediģēt</a
          >
        </button>
        <button
          class="btn btn-danger"
          data-bs-toggle="modal"
          data-bs-target="#my-modal-{{ product.product_id }}"
        >
          Dzēst
        </button>

        <div
          id="my-modal-{{ product.product_id }}"
          class="modal fade"
          tabindex="-1"
          role="dialog"
          aria-hidden="true"
        >
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content border-0">
              <div class="modal-body p-0">
                <div class="card border-0 p-sm-3 p-2 justify-content-center">
                  <div class="card-header pb-0 bg-white border-0">
                    <div class="row">
                      <div class="col ml-auto"></div>
                    </div>
                    <p class="font-weight-bold mb-2">
                      Vai Jūs esat pārliecināti ka vēlaties izdzēst šo produktu?
                    </p>
                  </div>
                  <div class="card-body px-sm-4 mb-2 pt-1 pb-0">
                    <div class="row justify-content-end no-gutters">
                      <div class="col-auto">
                        <button
                          type="button"
                          class="btn btn-light text-muted"
                          data-bs-dismiss="modal"
                        >
                          Atcelt
                        </button>
                      </div>
                      <div class="col-auto">
                        <form
                          action="{% url 'delete-product' product.product_id %}"
                          method="post"
                        >
                          {% csrf_token %}
                          <button type="submit" class="btn btn-danger">
                            Dzēst produktu
                          </button>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<div class="container" style="margin-top: 3rem">
  <div class="row" id="features">
    <div class="col-sm-7 feature text-center">
      <img class="prof_pic" src="{{ profile.foto.url }}" />
    </div>
    <div class="col-sm-5 feature profile">
      <p>Vārds: {{profile.first_name}}</p>
      <p>Uzvārds: {{profile.last_name}}</p>
      <p>Tālrunis: {{profile.phone}}</p>
      <p>E-pasts: {{profile.email}}</p>
      <div class="container">
        <button type="button" class="btn btn-secondary">
          <a href="{% url 'edit-profile' %}">Rediģēt profilu</a>
        </button>
      </div>
    </div>
  </div>
</div>

{% endif %} {% endblock %}

users/templates/users/profile_form.html
{% extends "main.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="container dform">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form|crispy }}
    <button type="submit">Saglabāt</button>
  </form>
</div>
{% endblock content %}

users/templates/users/select_group.html
<!DOCTYPE html> {% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Green Valley</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.14.0/css/all.css"
      integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc"
      crossorigin="anonymous"
    />
    <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
  </head>
  <body>
    <div
      class="container d-flex justify-content-center align-items-center vh-100"
    >
      <div class="row">
        <div class="col text-center">
          <h1>Vai esat klients vai saimniecība?</h1>
          <form method="post" action="{% url 'select-group' %}">
            {% csrf_token %}
            <input type="hidden" name="user_id" value="{{ user_id }}" />
            <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
              <button
                type="submit"
                name="group"
                value="client"
                class="btn btn-primary btn-lg btn-square"
              >
                Klients
              </button>
              <button
                type="submit"
                name="group"
                value="farm"
                class="btn btn-primary btn-lg btn-square"
              >
                Saimniecība
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>